# Generated by Django 5.0.6 on 2026-07-02 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('focus_area', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trainee_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Fellow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('education_background', models.CharField(max_length=255)),
                ('technical_interest', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('quote', models.CharField(blank=True, max_length=500)),
                ('placement_status', models.CharField(choices=[('in_training', 'In Training'), ('attachment', 'On Attachment'), ('employed', 'Employed'), ('self_employed', 'Self Employed'), ('seeking', 'Seeking Placement')], default='in_training', max_length=20)),
                ('portfolio_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fellows/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellows', to='cohorts.cohort')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('issuing_body', models.CharField(max_length=255)),
                ('awarded_date', models.DateField(blank=True, null=True)),
                ('badge', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('fellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cohorts.fellow')),
            ],
        ),
    ]
