# Generated by Django 5.0.6 on 2026-07-02 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('lab', 'Lab Session'), ('masterclass', 'Masterclass'), ('field_demo', 'Field Demo'), ('attachment', 'Attachment'), ('workshop', 'Workshop'), ('graduation', 'Graduation'), ('other', 'Other')], default='lab', max_length=20)),
                ('activity_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cohorts.cohort')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_date'],
            },
        ),
    ]
