# Generated by Django 5.0.6 on 2026-07-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='focus_areas',
            field=models.CharField(blank=True, help_text='Comma-separated list, e.g. Programme Funding, Industry Equipment, Youth Empowerment', max_length=500),
        ),
    ]
